language: python

python:
  - "3.6"
  
notifications:
  email: false
  
sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - TESTS="1" ODOO_REPO="odoo/odoo"

install:
  - pip install cachetools
  - pip install pdfconv
  - pip install anybox.testing.openerp
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
